<h1>Registro de Usuarios</h1>
<form name="registro_user" method="" action=""><input type="text" id="nombre_per" name="nombre_per"><input type="text" id="apellido_per" name="apellido_per"><input type="text" id="correo1_per" name="correo1_per"><input type="text" id="correo2_per" name="correo2_per"><input type="text" id="nombre_user" name="nombre_user"><input type="password" id="pass_user" name="pass_user"><select name="pais" id="pais"><option value="1">República de Abjasia</option>
<option value="2">Bases Soberanas de Acrotiri y Dhekelia</option>
<option value="3">República Islámica de Afganistán</option>
<option value="4">República de Albania</option>
<option value="5">República Federal de Alemania</option>
<option value="6">República del Alto Karabaj</option>
<option value="7">Principado de Andorra</option>
<option value="8">República de Angola</option>
<option value="9">Anguila</option>
<option value="10">Antigua y Barbuda</option>
<option value="11">Antillas Neerlandesas</option>
<option value="12">Reino de Arabia Saudita</option>
<option value="13">República Argelina Democrática y Popular</option>
<option value="14">República Argentina</option>
<option value="15">República de Armenia</option>
<option value="16">Aruba</option>
<option value="17">Mancomunidad de Australia</option>
<option value="18">República de Austria</option>
<option value="19">República de Azerbaiyán</option>
<option value="20">Mancomunidad de las Bahamas</option>
<option value="21">Reino de Bahréin</option>
<option value="22">República Popular de Bangladesh</option>
<option value="23">Barbados</option>
<option value="24">Reino de Bélgica</option>
<option value="25">Belice</option>
<option value="26">República de Benín</option>
<option value="27">Reconocimiento general</option>
<option value="28">Bermudas</option>
<option value="29">República de Bielorrusia</option>
<option value="30">Estado Plurinacional de Bolivia</option>
<option value="31">Reconocimiento general</option>
<option value="32">Bosnia y Herzegovina</option>
<option value="33">República de Botsuana</option>
<option value="34">República Federal del Brasil</option>
<option value="35">Estado de Brunéi, Morada de la Paz</option>
<option value="36">República de Bulgaria</option>
<option value="37">Burkina Faso (antes Rep. del Alto Volta)</option>
<option value="38">República de Burundi</option>
<option value="39">Reino de Bután</option>
<option value="40">República de Cabo Verde</option>
<option value="41">Islas Caimán</option>
<option value="42">Reino de Camboya</option>
<option value="43">República de Camerún</option>
<option value="44">Canadá</option>
<option value="45">República del Chad</option>
<option value="46">República de Chile</option>
<option value="47">Reconocimiento general</option>
<option value="48">República Popular China</option>
<option value="49">ONU</option>
<option value="50">República de Chipre</option>
<option value="51">República Turca del Norte de Chipre</option>
<option value="52">Islas Cocos</option>
<option value="53">República de Colombia</option>
<option value="54">Unión de las Comoras</option>
<option value="55">República del Congo</option>
<option value="56">República Democrática del Congo</option>
<option value="57">Islas Cook</option>
<option value="58">República Popular Democrática de Corea</option>
<option value="59">República de Corea</option>
<option value="60">República de Costa de Marfil</option>
<option value="61">Reconocimiento general</option>
<option value="62">República de Costa Rica</option>
<option value="63">República de Croacia</option>
<option value="64">República de Cuba</option>
<option value="65">Reino de Dinamarca</option>
<option value="66">Mancomunidad de Dominica</option>
<option value="67">República del Ecuador</option>
<option value="68">República Árabe de Egipto</option>
<option value="69">República de El Salvador</option>
<option value="70">Emiratos Árabes Unidos</option>
<option value="71">Estado de Eritrea</option>
<option value="72">República de Eslovaquia</option>
<option value="73">República de Eslovenia</option>
<option value="74">Reino de España</option>
<option value="75">Estados Unidos de América</option>
<option value="76">República de Estonia</option>
<option value="77">República Democrática Federal de Etiopía</option>
<option value="78">Islas Feroe</option>
<option value="79">República de las Filipinas</option>
<option value="80">República de Finlandia</option>
<option value="81">República de las Islas Fiyi (Fiji)</option>
<option value="82">República Francesa</option>
<option value="83">República Gabonesa</option>
<option value="84">República de la Gambia</option>
<option value="85">Georgia</option>
<option value="86">República de Ghana</option>
<option value="87">Gibraltar</option>
<option value="88">Granada</option>
<option value="89">República Helénica</option>
<option value="90">Groenlandia</option>
<option value="91">Isla Guam</option>
<option value="92">República de Guatemala</option>
<option value="93">Bailiazgo de Guernsey</option>
<option value="94">República de Guinea</option>
<option value="95">República de Guinea-Bissau</option>
<option value="96">República de Guinea Ecuatorial</option>
<option value="97">República Cooperativa de Guyana</option>
<option value="98">República de Haití</option>
<option value="99">República de Honduras</option>
<option value="100">Región Administrativa Especial de Hong Kong</option>
<option value="101">República de Hungría</option>
<option value="102">República de India</option>
<option value="103">República de Indonesia</option>
<option value="104">República Islámica de Irán</option>
<option value="105">República de Iraq</option>
<option value="106">República de Irlanda</option>
<option value="107">República de Islandia</option>
<option value="108">Estado de Israel</option>
<option value="109">Reconocimiento general, excepto 20+1 países</option>
<option value="110">República Italiana</option>
<option value="111">Jamaica</option>
<option value="112">Japón</option>
<option value="113">Bailiazgo de Jersey</option>
<option value="114">Reino Hachemita de Jordania</option>
<option value="115">República de Kazajistán</option>
<option value="116">República de Kenia</option>
<option value="117">República Kirguiza</option>
<option value="118">República de Kiribati</option>
<option value="119">República de Kosovo</option>
<option value="120">Estado de Kuwait</option>
<option value="121">República Democrática Popular Lao</option>
<option value="122">Reino de Lesoto</option>
<option value="123">República de Letonia</option>
<option value="124">República del Líbano</option>
<option value="125">República de Liberia</option>
<option value="126">Gran República Árabe Libia Popular y Socialista</option>
<option value="127">Principado de Liechtenstein</option>
<option value="128">República de Lituania</option>
<option value="129">Gran Ducado de Luxemburgo</option>
<option value="130">Región Administrativa Especial de Macao</option>
<option value="131">República de Macedonia[3]</option>
<option value="132">República de Madagascar</option>
<option value="133">Federación de Malasia</option>
<option value="134">Reconocimiento general</option>
<option value="135">República de Malaui</option>
<option value="136">República de las Maldivas</option>
<option value="137">República de Malí</option>
<option value="138">República de Malta</option>
<option value="139">Islas Malvinas</option>
<option value="140">Isla de Man</option>
<option value="141">Estado Libre Asociado de las Islas Marianas del Norte</option>
<option value="142">Reino de Marruecos</option>
<option value="143">República de las Islas Marshall</option>
<option value="144">República de Mauricio</option>
<option value="145">República Islámica de Mauritania</option>
<option value="146">Mayotte</option>
<option value="147">Estados Unidos Mexicanos</option>
<option value="148">Estados Federados de Micronesia</option>
<option value="149">República de Moldavia</option>
<option value="150">Principado de Mónaco</option>
<option value="151">Mongolia</option>
<option value="152">República de Montenegro</option>
<option value="153">Montserrat</option>
<option value="154">República de Mozambique</option>
<option value="155">Unión de Myanmar (antes Birmania)</option>
<option value="156">República de Namibia</option>
<option value="157">República de Nauru</option>
<option value="158">Territorio de la Isla de Navidad</option>
<option value="159">República Federal Democrática de Nepal</option>
<option value="160">República de Nicaragua</option>
<option value="161">República del Níger</option>
<option value="162">República Federal de Nigeria</option>
<option value="163">Niue</option>
<option value="164">Territorio de las Islas Norfolk</option>
<option value="165">Reino de Noruega</option>
<option value="166">Territorio de Nueva Caledonia y dependencias</option>
<option value="167">Nueva Zelanda</option>
<option value="168">Sultanato de Omán</option>
<option value="169">República de Osetia del Sur</option>
<option value="170">Reino de los Países Bajos</option>
<option value="171">Reconocimiento general</option>
<option value="172">República Islámica de Pakistán</option>
<option value="173">República de Palaos</option>
<option value="174">Autoridad Palestina de Cisjordania y la Franja de Gaza</option>
<option value="175">Administración transitoria autónoma de Israel.</option>
<option value="176">República de Panamá</option>
<option value="177">Estado Independiente de Papúa Nueva Guinea</option>
<option value="178">República del Paraguay</option>
<option value="179">República del Perú</option>
<option value="180">Islas Pitcairn</option>
<option value="181">Polinesia Francesa</option>
<option value="182">República de Polonia</option>
<option value="183">República Portuguesa</option>
<option value="184">Estado Libre Asociado de Puerto Rico</option>
<option value="185">Estado de Qatar</option>
<option value="186">Reino Unido de Gran Bretaña e Irlanda del Norte</option>
<option value="187">República Centroafricana</option>
<option value="188">República Checa</option>
<option value="189">República Dominicana</option>
<option value="190">República de Ruanda</option>
<option value="191">Rumania</option>
<option value="192">Federación Rusa</option>
<option value="193">República Árabe Saharaui Democrática</option>
<option value="194">Territorio de España de jure, ocupado por Marruecos de facto</option>
<option value="195">Islas Salomón</option>
<option value="196">Estado Independiente de Samoa</option>
<option value="197">Territorio de la Samoa Americana</option>
<option value="198">San Bartolomé</option>
<option value="199">Federación de San Cristóbal y Nieves</option>
<option value="200">Serenísima República de San Marino</option>
<option value="201">San Martín</option>
<option value="202">San Pedro y Miguelón</option>
<option value="203">San Vicente y las Granadinas</option>
<option value="204">Santa Helena</option>
<option value="205">Santa Lucía</option>
<option value="206">República Democrática de Santo Tomé y Príncipe</option>
<option value="207">República de Senegal</option>
<option value="208">República de Serbia</option>
<option value="209">República de Seychelles</option>
<option value="210">República de Sierra Leona</option>
<option value="211">República de Singapur</option>
<option value="212">República Árabe Siria</option>
<option value="213">Somalia</option>
<option value="214">República de Somalilandia</option>
<option value="215">República Democrática Socialista de Sri Lanka</option>
<option value="216">Reconocimiento general</option>
<option value="217">Reino de Suazilandia</option>
<option value="218">Reconocimiento general</option>
<option value="219">República de Sudáfrica</option>
<option value="220">Reconocimiento general</option>
<option value="221">República del Sudán</option>
<option value="222">Reino de Suecia</option>
<option value="223">Confederación Helvética</option>
<option value="224">República de Surinam</option>
<option value="225">Reino de Tailandia</option>
<option value="226">República de China</option>
<option value="227">República Unida de Tanzania</option>
<option value="228">República de Tayikistán</option>
<option value="229">República Democrática de Timor Oriental</option>
<option value="230">República Togoleña</option>
<option value="231">Tokelau</option>
<option value="232">Reino de Tonga</option>
<option value="233">República Moldava Pridnestroviana</option>
<option value="234">República de Trinidad y Tobago</option>
<option value="235">República Tunecina</option>
<option value="236">Islas Turcas y Caicos</option>
<option value="237">República de Turkmenistán</option>
<option value="238">República de Turquía</option>
<option value="239">Tuvalu</option>
<option value="240">Ucrania</option>
<option value="241">República de Uganda</option>
<option value="242">República Oriental del Uruguay</option>
<option value="243">República de Uzbekistán</option>
<option value="244">República de Vanuatu</option>
<option value="245">Estado de la Ciudad del Vaticano</option>
<option value="246" selected>República Bolivariana de Venezuela</option>
<option value="247">República Socialista de Vietnam</option>
<option value="248">Islas Vírgenes Británicas</option>
<option value="249">Islas Vírgenes de los Estados Unidos</option>
<option value="250">Islas Wallis y Futuna</option>
<option value="251">República de Yemen</option>
<option value="252">República de Yibuti</option>
<option value="253">República de Zambia</option>
<option value="254">República de Zimbabue</option>
</select>
</form>