<article class="grid_22 suffix_1">
                  <h3 align="left">¿Quienes Somos?</h3>
                  <h6 align="center">El Circuito Joropeando Online es la organizacion radial por internet mas grande de Venezuela y posee programas  en distintos estados del pais, conformando una alta audiencia, en todo el territorio nacional e internacional.</h6>
                  <p align="justify"> Contamos con el apoyo de diferentes paginas web del folklore: www.coplasllaneras.com desde el estado Yaracuy,  www.corazondelllano.com desde estado Barinas, www.musicallanera.net desde el estado carabobo, www.tupotro.com desde el estado yaracuy, www.rumbasllaneras.com desde el estado guarico y www.festivaleando.tk desde el estado portuguesa.  Pero los dos principales elementos que diferencian el Circuito es que apoyamos a todos los artistas por igual ya sean noveles o consagrados para nosotros tienen el mismo valor en este dificil mundo de la musica y que la emisora  cuenta con una programación las 24 horas del dia los 365 días del año, de solo musica llanera. Contamos con los mejores programas, y los mas calificados locutores para brindarles y  satisfacer las necesidades  y expectativas de los diferentes oyentes a nivel mundial.</p>
                <p align="justify"><strong>MISIÓN:</strong> Apoyar el desarrollo cultural a través de la poyeccion y promociona  con calidad, honestidad y compromiso.</p>
                <p align="justify"><strong>VISIÓN: </strong>Ser un medio de comunicación social con alto nivel de efectividad  en su gestión acorde a un perfil profesional y técnico.</p>
                <p align="justify"><strong>POLITICAS:</strong> Servicio de radio difusión que brinde espacios de recreación,  educación e información. Fortalecimiento empresarial con una estructura y niveles de organización bien definidas, promoción y Proyeccion del talento regional, nacional e internacional.</p>
                <p align="left">Directora: <strong>Mariangel Anguiz</strong></p>
                <p align="left">Director De Operaciones: <strong>Gabriel Gutierrez </strong></p>
                <p align="left">&nbsp;</p>
                <p align="center">Es por eso que el Circuito Joropeando Online esta Rompiendo Fronteras A Nivel Mundial</p>
                <p align="left">&nbsp;</p>
                <h6 align="left">&nbsp;</h6>
